repository: TechHoldingLLC/labs-theme
title: TH Labs Theme
description: >
  This is the Jekyll Theme for Tech Holding Labs GitHub Pages

# Date format
# refer to https://ruby-doc.org/core-3.0.0/Time.html#method-i-strftime if you want to customize this
labs:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    github:  TechHoldingLLC
    facebook: techholding
    linkedin: tech-holding

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
# - docs/index.md
pages:
  - docs/index.md

# Build settings
theme: labstheme

plugins:
 - jekyll-seo-tag
