repository: TechHoldingLLC/labs-theme
title: TH Labs Theme
description: >
  This is the Jekyll Theme for Tech Holding Labs GitHub Pages

# Date format
# refer to https://ruby-doc.org/core-3.0.0/Time.html#method-i-strftime if you want to customize this
labs:
  date_format: "%b %-d, %Y"

  base_url: "https://labs.techholding.co"

  # generate social links in footer
  social_links:
    github:  TechHoldingLLC
    facebook: techholding
    linkedin: tech-holding

featured:
  - name: Marvelous project
    desc: This is a description
    repo_slug: test
    image: assets/img/default.png

# Build settings
theme: labstheme

plugins:
 - jekyll-seo-tag
